# Generated by Django 6.0.3 on 2026-03-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_network_admin',
            field=models.BooleanField(default=False, help_text='Grants access to the AetherNode Admin Console'),
        ),
    ]
