# Generated by Django 6.0.3 on 2026-03-07 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_ttl_days', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'messaging_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sender_did', models.CharField(db_index=True, max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File Attachment'), ('image', 'Image'), ('voice', 'Voice Note'), ('system', 'System Event')], default='text', max_length=20)),
                ('encrypted_body', models.TextField()),
                ('dht_key', models.CharField(blank=True, max_length=128, null=True)),
                ('node_endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_size', models.BigIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('credits_charged', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('search_vector', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
            ],
            options={
                'db_table': 'messaging_message',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reader_did', models.CharField(db_index=True, max_length=255)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='messaging.message')),
            ],
            options={
                'db_table': 'messaging_message_receipt',
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('did', models.CharField(db_index=True, max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('encrypted_group_key', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.conversation')),
            ],
            options={
                'db_table': 'messaging_conversation_member',
                'unique_together': {('conversation', 'did')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='messaging_m_convers_118d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_did'], name='messaging_m_sender__8ceade_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereceipt',
            unique_together={('message', 'reader_did')},
        ),
    ]
