# Generated by Django 6.0.3 on 2026-03-07 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeWallet',
            fields=[
                ('node_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('earned_balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('did', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=8, default=100.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('storage_payment', 'Storage Payment'), ('node_payout', 'Node Payout')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.nodewallet')),
                ('user_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.userwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
