# Generated by Django 6.0.3 on 2026-03-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('tx_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('sender_address', models.CharField(db_index=True, max_length=64)),
                ('recipient_address', models.CharField(db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('signature', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'billing_ledger_transaction',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='nodewallet',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
