# Generated by Django 6.0.3 on 2026-03-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_ledgertransaction_nodewallet_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('storage_payment', 'Storage Payment'), ('node_payout', 'Node Payout'), ('transfer_in', 'Incoming Transfer'), ('transfer_out', 'Outgoing Transfer')], max_length=20),
        ),
    ]
