import os
import hashlib
from pathlib import Path
from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.hazmat.primitives import serialization, hmac, hashes

# Path to the user-provided wordlist
BASE_DIR = Path(__file__).resolve().parent.parent.parent
WORDLIST_PATH = BASE_DIR / 'bip-39-wordlist' / 'bip39_wordlist_mnemonics_english.txt'

def get_wordlist():
    if not WORDLIST_PATH.exists():
        raise FileNotFoundError(f"BIP-39 wordlist not found at {WORDLIST_PATH}")
    with open(WORDLIST_PATH, 'r', encoding='utf-8') as f:
        return [line.strip() for line in f if line.strip()]

def generate_mnemonic() -> str:
    """Generates a 12-word BIP-39 mnemonic phrase."""
    wordlist = get_wordlist()
    # 128 bits of entropy (16 bytes)
    entropy = os.urandom(16)
    
    # Calculate checksum (first 4 bits of SHA256(entropy))
    hash_bytes = hashlib.sha256(entropy).digest()
    checksum = bin(hash_bytes[0])[2:].zfill(8)[:4]
    
    # Convert entropy to binary string
    entropy_bin = ''.join(bin(byte)[2:].zfill(8) for byte in entropy)
    
    # Combine (132 bits total)
    total_bin = entropy_bin + checksum
    
    # Split into 11-bit chunks to get indices
    mnemonic = []
    for i in range(0, len(total_bin), 11):
        chunk = total_bin[i:i+11]
        idx = int(chunk, 2)
        mnemonic.append(wordlist[idx])
        
    return ' '.join(mnemonic)

def mnemonic_to_seed(mnemonic: str, passphrase: str = "") -> bytes:
    """Generate cryptographic seed from mnemonic using PBKDF2 HMAC-SHA512."""
    salt = ("mnemonic" + passphrase).encode('utf-8')
    seed = hashlib.pbkdf2_hmac(
        'sha512',
        mnemonic.encode('utf-8'),
        salt,
        2048,
        64
    )
    return seed

def derive_keypair(mnemonic: str) -> dict:
    """
    Derives an Ed25519 keypair and standard ath1 wallet address from a mnemonic.
    """
    seed = mnemonic_to_seed(mnemonic)
    # Ed25519 takes 32 bytes of seed
    private_key = ed25519.Ed25519PrivateKey.from_private_bytes(seed[:32])
    public_key = private_key.public_key()
    
    # Export raw bytes
    priv_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption()
    )
    pub_bytes = public_key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw
    )
    
    # Hash public key for address mapping
    pub_hash = hashlib.sha256(pub_bytes).hexdigest()
    
    # Generate AetherStore address (Prefix + first 40 chars of hash)
    address = f"ath1{pub_hash[:40]}"
    did = f"did:aether:{address}"
    
    return {
        'mnemonic': mnemonic,
        'private_key': priv_bytes.hex(),
        'public_key': pub_bytes.hex(),
        'address': address,
        'did': did
    }

def sign_message(private_key_hex: str, message: str) -> str:
    """Cryptographically sign a string message."""
    priv_bytes = bytes.fromhex(private_key_hex)
    private_key = ed25519.Ed25519PrivateKey.from_private_bytes(priv_bytes)
    signature = private_key.sign(message.encode('utf-8'))
    return signature.hex()

def verify_signature(public_key_hex: str, message: str, signature_hex: str) -> bool:
    """Verify an Ed25519 signature generated by sign_message."""
    try:
        pub_bytes = bytes.fromhex(public_key_hex)
        public_key = ed25519.Ed25519PublicKey.from_public_bytes(pub_bytes)
        sig_bytes = bytes.fromhex(signature_hex)
        public_key.verify(sig_bytes, message.encode('utf-8'))
        return True
    except Exception:
        return False
def sign_with_secret(secret_key: str, message: str) -> str:
    """Sign a message using an HMAC secret key (System-level trust)."""
    h = hmac.HMAC(secret_key.encode('utf-8'), hashes.SHA256())
    h.update(message.encode('utf-8'))
    return h.finalize().hex()

def verify_with_secret(secret_key: str, message: str, signature_hex: str) -> bool:
    """Verify an HMAC signature using a shared secret."""
    try:
        h = hmac.HMAC(secret_key.encode('utf-8'), hashes.SHA256())
        h.update(message.encode('utf-8'))
        h.verify(bytes.fromhex(signature_hex))
        return True
    except Exception:
        return False
