# Generated by Django 6.0.3 on 2026-03-06 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('owner_did', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'storage_bucket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=64, unique=True)),
                ('endpoint', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('capacity_bytes', models.BigIntegerField(default=0)),
                ('used_bytes', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'storage_node',
            },
        ),
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner_did', models.CharField(max_length=255, unique=True)),
                ('quota_bytes', models.BigIntegerField(default=10737418240)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'storage_quota',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner_did', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret', models.CharField(default=uuid.uuid4, max_length=64)),
            ],
            options={
                'db_table': 'storage_webhook',
            },
        ),
        migrations.CreateModel(
            name='StorageObject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('owner_did', models.CharField(max_length=255)),
                ('shard_map', models.JSONField(default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_objects', to='storage.bucket')),
            ],
            options={
                'db_table': 'storage_object',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_did', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=20)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField(default=200)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='storage.storageobject')),
            ],
            options={
                'db_table': 'storage_access_log',
            },
        ),
        migrations.AddIndex(
            model_name='storageobject',
            index=models.Index(fields=['content_hash'], name='storage_obj_content_e7cc74_idx'),
        ),
        migrations.AddIndex(
            model_name='storageobject',
            index=models.Index(fields=['owner_did', '-created_at'], name='storage_obj_owner_d_b5959d_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['timestamp'], name='storage_acc_timesta_d4c8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user_did', 'timestamp'], name='storage_acc_user_di_5b2c35_idx'),
        ),
    ]
