# Generated by Django 6.0.3 on 2026-03-06 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('owner_did', models.CharField(db_index=True, max_length=255)),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('key_hash', models.CharField(db_index=True, max_length=64)),
                ('root_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('merkle_dag', models.JSONField(default=dict)),
                ('chunk_count', models.IntegerField(default=0)),
                ('chunk_size', models.IntegerField(default=262144)),
                ('original_size', models.BigIntegerField()),
                ('original_hash', models.CharField(max_length=64)),
                ('mime_type', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('shard_map', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_objects', to='storage.bucket')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='storage.encryptedobject')),
            ],
            options={
                'db_table': 'storage_encrypted_object',
            },
        ),
        migrations.CreateModel(
            name='ObjectVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('root_hash', models.CharField(max_length=64)),
                ('original_size', models.BigIntegerField()),
                ('original_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='storage.encryptedobject')),
            ],
            options={
                'db_table': 'storage_object_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='encryptedobject',
            index=models.Index(fields=['owner_did', '-created_at'], name='storage_enc_owner_d_efb724_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedobject',
            index=models.Index(fields=['root_hash'], name='storage_enc_root_ha_0aa134_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedobject',
            index=models.Index(fields=['bucket', 'is_deleted'], name='storage_enc_bucket__37b59d_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedobject',
            index=models.Index(fields=['original_hash'], name='storage_enc_origina_3b6bab_idx'),
        ),
        migrations.AddIndex(
            model_name='objectversion',
            index=models.Index(fields=['object', '-version_number'], name='storage_obj_object__cda835_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='objectversion',
            unique_together={('object', 'version_number')},
        ),
    ]
