# Generated by Django 6.0.3 on 2026-03-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_encryptedobject_objectversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageobject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
