# Generated by Django 6.0.3 on 2026-03-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storageobject_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedobject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
