# Generated by Django 6.0.3 on 2026-03-06 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_encryptedobject_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('owner_did', models.CharField(db_index=True, max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('total_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='initialized', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='storage.bucket')),
            ],
            options={
                'db_table': 'storage_upload_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadPart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('part_number', models.IntegerField()),
                ('size', models.IntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('temp_filepath', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='storage.uploadsession')),
            ],
            options={
                'db_table': 'storage_upload_part',
                'ordering': ['part_number'],
                'unique_together': {('session', 'part_number')},
            },
        ),
    ]
