# Generated by Django 6.0.3 on 2026-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_uploadsession_uploadpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagenode',
            name='average_latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storagenode',
            name='failed_retrievals',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storagenode',
            name='reputation_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='storagenode',
            name='successful_retrievals',
            field=models.BigIntegerField(default=0),
        ),
    ]
