# Generated by Django 6.0.3 on 2026-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_storagenode_average_latency_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectversion',
            name='merkle_dag',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='objectversion',
            name='shard_map',
            field=models.JSONField(default=dict),
        ),
    ]
