# Generated by Django 6.0.3 on 2026-03-07 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_objectversion_merkle_dag_objectversion_shard_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('owner_did', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_records', to='storage.encryptedobject')),
            ],
            options={
                'db_table': 'storage_name_record',
                'ordering': ['-updated_at'],
            },
        ),
    ]
