# Generated by Django 6.0.3 on 2026-03-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_namerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='object',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='object_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
