# Generated by Django 6.0.3 on 2026-03-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_remove_accesslog_object_accesslog_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkParameter',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'p2p_network_parameter',
            },
        ),
        migrations.AddField(
            model_name='storagenode',
            name='owner_did',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MiningReward',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('reward_type', models.CharField(choices=[('storage', 'Proof of Storage'), ('service', 'Proof of Service')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='storage.storagenode')),
            ],
            options={
                'db_table': 'storage_mining_reward',
                'ordering': ['-timestamp'],
            },
        ),
    ]
